### ISSUE TITLE
Broken Button 👇🏿

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#10]
We have a button on our homepage, that is unfortunately not working. Let's squish this bug:

- [] open `./js/button.js`
- [] Fix the code so that the button successfully triggers an action on click.
- [] Merge the file into master
- [] Add a comment to your PR, explaining the original problem and your fix.

Please submit your PR with a checklist, showing that you have done these three things. 

BONUS: Improve the button by adding design elements and making it do something more interesting - for example toggling a photo!
BONUS: Squash your commits.

**Comment by KaurManjot** [comment]
Working on this one!!

**Comment by VerteDinde** [comment]
Thank you @KaurManjot !

**Comment by mukul7** [comment]
Is It open?
