### ISSUE TITLE
Knock Knock, Help! 🚪

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#14]
Our client is a very awkward person; she needs some help breaking the ice, and would like a quick guide.

- [] Create a new file in `doc` called `jokes.md`
- [] Add whatever jokes you'd like to the md file.
- [] Merge the file into master
- [] Add a comment to your PR, explaining the original problem and your fix.

Please submit your PR with a checklist, showing that you have done these things. 

BONUS: Squash your commits.

**Comment by KatSaldivar** [comment]
We'd be happy to help out with this issue if no one else has claimed it!

**Comment by VerteDinde** [comment]
Thank you @KatSaldivar !
