### ISSUE TITLE
Needs More Nick Cage 🕺🏻

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#2]
Our client likes the site, but wants us to have `More Nick Cage` before our first release. We need:

 - [x] Create a new `html` file called 'nick.html'.
 - [x] Grab two photos from [PlaceCage](https://www.placecage.com/) and put them into the file
 - [x] Merge the file into master

Please submit your PR with a checklist, showing that you have done these three things. BONUS: Squash your commits.

**Comment by shanselman** [comment]
I'll take this if that's OK

**Comment by VerteDinde** [comment]
That great, Scott! Go for it! Please reference this issue in your PR. :)

**Comment by shanselman** [comment]
I'm super confused. Do you want a NEW checklist or should check yours? Happy to do either!

**Comment by VerteDinde** [comment]
Hi Scott: Great question - we need to be clearer. Please copy the checklist and confirm that you completed all steps - it makes our jobs easier. Thanks! :)

**Comment by VerteDinde** [comment]
We need more Nick Cage or Morgan Freeman!
