### ISSUE TITLE
Cupcake Me! 🍰

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#3]
Our client is extremely into cupcakes, and would like us to show our love for cupcakes as well. We need to:

 - [ ] Open the index.html file
 - [ ] Grab text from [Cupcake Ipsum](http://www.cupcakeipsum.com/) and add it to the index page.
 - [ ] Merge the index page into the main repo.

Please submit your PR with a checklist, showing that you have done these three things. 

BONUS #1: Add a cupcake picture with the cupcake text.
BONUS #2: Squash your commits.

**Comment by jennifer-kinsey** [comment]
We got cupcake!

**Comment by VerteDinde** [comment]
Awesome, thanks @jennifer-kinsey !
