### ISSUE TITLE
The Magic Python 🐍

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#4]
Our client would like start collecting data on who's visiting our website. Unfortunately, rather than using actual plug-ins, our client would like us to write and use a Magic 8 Ball program to tell them if the website is popular.

To do this, we need to use a written Python script for Magic 8 Ball, but we think the Magic 8 Ball's messages are rather boring. To fix it, please do the following: 

 - [ ] Open the `utils/python` folder and the `magic-8-ball` file.
 - [ ] Change some of the magic 8 ball messages to messages of your choice.
 - [ ] Merge the file into master

Please submit your PR with a checklist, showing that you have done these three things.
 
BONUS #1: Refactor the Python code for an even better script.
BONUS #2: Squash your commits.

**Comment by jinzhong2** [comment]
Can I take #4?

**Comment by VerteDinde** [comment]
Absolutely! Please do!

**Comment by jinzhong2** [comment]
@VerteDinde: First, python is in the root directory, not under utils/
2nd, how do I test my change before commit?
Thanks.

**Comment by VerteDinde** [comment]
Sorry @jinzhong2 we don't have a test suite set up for the Python utils yet, but I can review it!

**Comment by jinzhong2** [comment]
@VerteDinde I'm ready to merge (already updated my github tree).  I have tested it standalone. How do I generate a pull request? I clicked a new pull request, and put my github link, but it says nothing is different?
