### ISSUE TITLE
Cursive Only 🖌

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#5]
Our client does not care for the dull font our website is currently using - they've requested something 'wild, with a lot of pop.' Please fix by:

 - [] Choose a font from [Google Fonts](https://fonts.google.com/) that is either cursive or extremely strange
 - [] Open `./css/main.css` and import the font at the top of the CSS file.
 - [] On line 17, change the `font-family` to your font.
 - [] Change the color to whatever color you'd like.
 - [] Merge the file into master

Please submit your PR with a checklist, showing that you have done these three things. 

BONUS: Squash your commits, if needed.

**Comment by jastr945** [comment]
Sharlee and Polina will take this one!

**Comment by VerteDinde** [comment]
Sounds great!
