### ISSUE TITLE
Cats vs Dogs? 🐶  🐱

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#6]
Our client has asked us to decide the ultimate question - cats or dogs? We can't possibly choose one, so we thought - why not both?

- [] Open `index.html`
- [] Grab a placeholder image from [PlaceKitten](https://placekitten.com/) and add it to the index.html page. You can choose the size.
- [] Grab a placeholder image from a Google image search of puppies. Add the puppy photo to our repo to the `img` directory. Link to that image in the `index.html` page.
- [] Merge the file into master

Please submit your PR with a checklist, showing that you have done these three things. 

BONUS: Squash your commits.

**Comment by merylturner** [comment]
Stephanie and I will take this one!

**Comment by VerteDinde** [comment]
Please do!
