### ISSUE TITLE
Bad Docs, Bad Recipe 🍒

### ISSUE THREAD

**Issue by VerteDinde** [wwcodeportland/intro-to-open-source#8]
A chef has kindly provided us with a markdown file of her best cherry pie recipe, which we will eventually convert to HTML and add to the website. Unfortunately, while the chef is an excellent baker, she is not very good at documentation. Steps are missing from her recipe, and typos are everywhere.

- [] Open `recipe.md`
- [] Fix the typos in the recipe and add any steps that you think are missing.
- [] Merge the file into master

Please submit your PR with a checklist, showing that you have done these three things. 

BONUS #1: Completely throw out the old recipe and add in your own.
BONUS #2: Squash your commits.

**Comment by sharz1** [comment]
Can I take a stab at this one?
